apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app-backend
  description: App manager backend
  tags:
    - nodejs
    - backend
spec:
  type: service
  lifecycle: production
  owner: misanche
